pipeline {
    agent any
    stages {
        stage('1') {
            steps {
                echo "print 1"
            }
        }
        stage('2') {
            steps {
                echo "print 2"
            }
        }
        stage('3') {
            steps {
                echo "print 3"
            }
        }
    }
}
